using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

public class Program {
    public static void Main() {
        var files = new[] { "ImpactCalculationScreen.kt", "InterpolationScreen.kt", "MapScreen.kt", "ProjectListScreen.kt", "ReverseCalculationScreen.kt", "SettingsScreen.kt" };
        
        var replacements = new Dictionary<string, string> {
            { "Hesab\uFFFD", "Hesabı" },
            { "Ge\uFFFDmi\uFFFD", "Geçmiş" },
            { "ge\uFFFDmi\uFFFDe", "geçmişe" },
            { "Men\uFFFD", "Menü" },
            { "\uFFFD\uFFFDlem", "İşlem" },
            { "Ge\uFFFDmi\uFFFDi", "Geçmişi" },
            { "Y\uFFFDkle", "Yükle" },
            { "y\uFFFDklensin", "yüklensin" },
            { "\uFFFDzerine", "Üzerine" },
            { "yaz\uFFFDlacak", "yazılacak" },
            { "\uFFFDptal", "İptal" },
            { "Se\uFFFDildi", "Seçildi" },
            { "Se\uFFFD ", "Seç " },
            { "Se\uFFFD\n", "Seç\n" },
            { "Se\uFFFD\"", "Seç\"" },
            { "T\uFFFDm\uFFFDn\uFFFD", "Tümünü" },
            { "Payla\uFFFD", "Paylaş" },
            { "Hatas\uFFFD", "Hatası" },
            { "Hen\uFFFDz", "Henüz" },
            { "kay\uFFFDt", "kayıt" },
            { "hesab\uFFFD", "hesabı" },
            { "sonu\uFFFDlar\uFFFDn\uFFFDz", "sonuçlarınız" },
            { "g\uFFFDr\uFFFDnecek", "görünecek" },
            { "y\uFFFDklemek", "yüklemek" },
            { "i\uFFFDin", "için" },
            { "bas\uFFFDn", "basın" },
            { "\uFFFDst", "Üst" },
            { "Sat\uFFFDr", "Satır" },
            { "Ba\uFFFDl\uFFFDk", "Başlık" },
            { "Bacal\uFFFD", "Bacalı" },
            { "T\uFFFDm", "Tüm" },
            { "Hatal\uFFFD", "Hatalı" },
            { "E\uFFFDim", "Eğim" },
            { "Aral\uFFFD\uFFFD\uFFFD", "Aralığı" },
            { "e\uFFFDim", "eğim" },
            { "Detaylar\uFFFD", "Detayları" },
            { "B\uFFFDLG\uFFFDLER\uFFFD", "BİLGİLERİ" },
            { "ANAL\uFFFDZLER\uFFFD", "ANALİZLERİ" },
            { "ANAL\uFFFDLER\uFFFD", "ANALİZLERİ" }, // just in case
            { "noktas\uFFFD", "noktası" },
            { "ad\uFFFD", "adı" },
            { "fark\uFFFD", "farkı" },
            { "y\uFFFDkle", "yükle" },
            { "Bile\uFFFDenler", "Bileşenler" },
            { "de\uFFFD\uFFFDi\uFFFDmedi", "değişmedi" },
            { "de\uFFFD\uFFFD\uFFFDmedi", "değişmedi" },
            { "S\uFFFDf\uFFFDrla", "Sıfırla" },
            { "\uFFFDNER\uFFFDLEN", "ÖNERİLEN" },
            { "aral\uFFFDk", "aralık" },
            { "tamamlay\uFFFDn", "tamamlayın" },
            { "bacalar\uFFFDn", "bacaların" },
            { "t\uFFFDm", "tüm" },
            { "s\uFFFDn\uFFFDrlar\uFFFDn\uFFFD", "sınırlarını" },
            { "sa\uFFFDl\uFFFDyor", "sağlıyor" },
            { "Baz\uFFFD", "Bazı" },
            { "hatlar\uFFFDn", "hatların" },
            { "e\uFFFDimi", "eğimi" },
            { "s\uFFFDn\uFFFDrlar\uFFFDn", "sınırların" },
            { "d\uFFFD\uFFFD\uFFFDnda", "dışında" },
            { "PROF\uFFFDL", "PROFİL" },
            { "ili\uFFFDkisi", "ilişkisi" },
            { "Ak\uFFFD\uFFFD", "Akış" },
            { "y\uFFFDn\uFFFD", "yönü" },
            { "Giri\uFFFDleteri", "Girişleri" },
            { "DE\uFFFD\uFFFDERLER\uFFFD", "DEĞERLERİ" },
            { "Ba\uFFFDlang\uFFFD\uFFFD", "Başlangıç" },
            { "Biti\uFFFD", "Bitiş" },
            { "Kart\uFFFD", "Kartı" },
            { "g\uFFFDstergesi", "göstergesi" },
            { "giri\uFFFDi", "girişi" },
            { "giri\uFFFD", "giriş" },
            { "Sonu\uFFFD", "Sonuç" },
            { "Y\uFFFDn", "Yön" },
            { "D\uFFFD\uFFFD\uFFFD\uFFFD", "Düşüş" },
            { "y\uFFFDn\uFFFDnde", "yönünde" },
            { "Y\uFFFDkselei\uFFFD", "Yükseliş" },
            { "D\uFFFDz", "Düz" },
            { "Diyagram\uFFFD", "Diyagramı" },
            { "G\uFFFDster", "Göster" },
            { "arale\uFFFDk", "aralık" },
            { "se\uFFFDimi", "seçimi" },
            { "ba\uFFFDl\uFFFD\uFFFD\uFFFD", "başlığı" },
            { "sat\uFFFDrlar\uFFFD", "satırları" },
            { "Se\uFFFDilen", "Seçilen" },
            { "a\uFFFD\uFFFDlamad\uFFFD", "açılamadı" },
            { "okunamad\uFFFD", "okunamadı" },
            { "a\uFFFD\"", "aç\"" },
            { "format\uFFFDnda", "formatında" },
            { "do\uFFFD\uFFFD-bat\uFFFD", "doğu-batı" },
            { "do\uFFFD-bat\uFFFD", "doğu-batı" },
            { "kuzey-g\uFFFDney", "kuzey-güney" },
            { "hen\uFFFDz", "henüz" },
            { "bo\uFFFD", "boş" },
            { "Ba\uFFFDlamak", "Başlamak" },
            { "di\uFFFDerine", "diğerine" },
            { "s\uFFFDr\uFFFDkleyin", "sürükleyin" },
            { "Ad\uFFFD", "Adı" },
            { "\uFFFDrn", "Örn" },
            { "\uFFFDizimi", "Çizimi" },
            { "hatt\uFFFD", "hattı" },
            { "veritaban\uFFFDndan", "veritabanından" },
            { "Vazge\uFFFD", "Vazgeç" },
            { "bacas\uFFFD", "bacası" },
            { "ba\uFFFDl\uFFFD", "bağlı" },
            { "hatlar\uFFFD", "hatları" },
            { "\uFFFD\uFFFDe", "İçe" },
            { "haz\uFFFDr", "hazır" },
            { "Veritaban\uFFFDna", "Veritabanına" },
            { "tamamland\uFFFD", "tamamlandı" },
            { "ge\uFFFDerli", "geçerli" },
            { "ge\uFFFDersiz", "geçersiz" },
            { "sat\uFFFDr", "satır" },
            { "i\uFFFDlemde", "işlemde" },
            { "veritaban\uFFFDna", "veritabanına" },
            { "Bacay\uFFFD", "Bacayı" },
            { "D\uFFFDzenle", "Düzenle" },
            { "\uFFFDmalat", "İmalat" },
            { "yap\uFFFDlemad\uFFFD", "yapılamadı" },
            { "yap\uFFFDled\uFFFD", "yapıldı" },
            { "Hakedi\uFFFDe", "Hakedişe" },
            { "Fark\uFFFD", "Farkı" },
            { "Hakedi\uFFFD", "Hakediş" },
            { "\uFFFDmalatta", "İmalatta" },
            { "Hakedi\uFFFDte", "Hakedişte" },
            { "Planland\uFFFD", "Planlandı" },
            { "E\uFFFDimi", "Eğimi" },
            { "Ba\uFFFDla", "Başla" },
            { "G\uFFFDr\uFFFDn\uFFFDm\uFFFD", "Görünümü" },
            { "s\uFFFDf\uFFFDrla", "sıfırla" },
            { "Ka\uFFFD\uFFFDnc\uFFFD", "Kaçıncı" },
            { "hakedi\uFFFD\uFFFD", "hakediş?" },
            { "bacas\uFFFDn\uFFFDn", "bacasının" },
            { "oledu\uFFFD\uFFFD", "olduğu" },
            { "numaras\uFFFDn\uFFFD", "numarasını" },
            { "numaras\uFFFD", "numarası" },
            { "Foto\uFFFDraflardan", "Fotoğraflardan" },
            { "\uFFFDnce", "Önce" },
            { "b\uFFFDl\uFFFDm\uFFFDnden", "bölümünden" },
            { "ba\uFFFDl\uFFFDk", "başlık" },
            { "tan\uFFFDmlay\uFFFDn", "tanımlayın" },
            { "se\uFFFDin", "seçin" },
            { "A\uFFFD\uFFFDklama", "Açıklama" },
            { "iste\uFFFDe", "isteğe" },
            { "foto\uFFFDraf\uFFFD", "fotoğrafı" },
            { "Foto\uFFFDraf", "Fotoğraf" },
            { "Kayd\uFFFD", "Kaydı" },
            { "\uFFFDMALAT", "İMALAT" },
            { "HAKED\uFFFD\uFFFD", "HAKEDİŞ" },
            { "Sa\uFFFDa", "Sağa" },
            { "hakedi\uFFFDe", "hakedişe" },
            { "g\uFFFDnder", "gönder" },
            { "ekran\uFFFDnda", "ekranında" },
            { "bacalar\uFFFD", "bacaları" },
            { "ba\uFFFDlay\uFFFDn", "başlayın" },
            { "\uFFFDmalata", "İmalata" },
            { "G\uFFFDnder", "Gönder" },
            { "kaz\uFFFD", "kazı" },
            { "derinlei\uFFFDi", "derinliği" },
            { "B\uFFFDL\uFFFDNEN", "BİLİNEN" },
            { "Ba\uFFFDleang\uFFFD\uFFFD", "Başlangıç" },
            { "Se\uFFFD\uFFFDici", "Seçici" },
            { "Y\uFFFDn\uFFFD", "Yönü" },
            { "\uFFFDstenen", "İstenen" },
            { "Kar\uFFFD\uFFFDt", "Karşıt" },
            { "g\uFFFDsterimi", "gösterimi" },
            { "E\uFFFDer", "Eğer" },
            { "g\uFFFDster", "göster" },
            { "Y\uFFFDzde", "Yüzde" },
            { "Derinli\uFFFDi", "Derinliği" },
            { "\uFFFDnerilen", "Önerilen" },
            { "aral\uFFFD\uFFFD\uFFFDn\uFFFD", "aralığını" },
            { "al\uFFFDn\uFFFDr", "alınır" },
            { "Uyar\uFFFD", "Uyarı" },
            { "E\uFFFD\uFFFDi\uFFFDi", "Eşiği" },
            { "e\uFFFD\uFFFDi\uFFFDi", "eşiği" },
            { "de\uFFFDeri", "değeri" },
            { "a\uFFFD\uFFFDnca", "aşınca" },
            { "uyar\uFFFD", "uyarı" },
            { "g\uFFFDsterilir", "gösterilir" },
            { "Numaras\uFFFD", "Numarası" },
            { "notlar\uFFFDn\uFFFDn", "notlarının" },
            { "etiketlenece\uFFFDi", "etiketleneceği" },
            { "Ba\uFFFDl\uFFFDklar", "Başlıklar" },
            { "kay\uFFFDtlar\uFFFDnda", "kayıtlarında" },
            { "se\uFFFDilecek", "seçilecek" },
            { "ba\uFFFDl\uFFFDklar\uFFFD", "başlıkları" },
            { "Do\uFFFDrusall\uFFFD\uFFFD\uFFFD", "Doğrusallığı" },
            { "tan\uFFFDmlanmad\uFFFD", "tanımlanmadı" },
            { "ba\uFFFDl\uFFFD\uFFFD\uFFFDn\uFFFD", "başlığını" },
            { "Hakk\uFFFDnda", "Hakkında" }
        };
        
        foreach (var file in files) {
            var path = "app/src/main/java/com/example/egimhesabi/ui/screens/" + file;
            var content = File.ReadAllText(path, Encoding.UTF8);
            
            // First we must sort keys by length descending to replace longest patterns first!
            var keys = new List<string>(replacements.Keys);
            keys.Sort((a, b) => b.Length.CompareTo(a.Length));
            
            foreach (var key in keys) {
                content = content.Replace(key, replacements[key]);
            }
            
            File.WriteAllText(path, content, new UTF8Encoding(false));
            Console.WriteLine("Fixed replacements in " + file);
        }
    }
}
